# frozen_string_literal: true

FILTER_ARTISTS_LIST = [
  'Habstrakt',
  'TroyBoi',
  'Weezer',
  'Maxo',
  'SWANES',
  'Lully',
  'Virtual Riot',
  'JOYRYDE',
  'Dillon Francis',
  'Ruby Empress',
  'WRLD',
  'Traxwell',
  'Rationale',
  'courtship',
  'Mat Zo',
  'Knife Party',
  'KSHMR',
  'Zedd',
  'Botnek',
  'Flume',
  'Boombox Cartel',
  'Kero Kero Bonito',
  'RKCB',
  'Tennyson',
  'PREP',
  'sundial',
  'Galantis',
  'Porter Robinson',
  'Gavin Turek',
  'Chiara Hunter',
  "Skogsr\xC3\xA5",
  'Skogsra',
  'SOPHIE',
  'Curbi',
  'Skylar Spence',
  'AWE',
  'Wave Racer',
  'Diveo',
  'Tundran',
  'Gammer',
  'Caravan Palace',
  'aivi & surasshu',
  'Lenno',
  'Billboard',
  'Robotaki',
  'Fox Stevenson',
  'Jay Prince',
  'RL Grime',
  "Cosmo's Midnight",
  'Goodnight Cody',
  'OK Go',
  'Chloe Martini',
  'Noisia',
  'bo en',
  'Disclosure',
  'Mystery Skulls',
  'ANAMANAGUCHI',
  'Jakubi',
  'Chromeo',
  'TOKYO MACHINE',
  'slenderbodies',
  'Haywyre',
  'grey',
  'Magic Man',
  'Lido',
  'Urban Cone',
  'Madeon',
  'CHVRCHES',
  'KOAN Sound',
  'The Colourist',
  'Chad Valley',
  'Aero Chord',
  'Charlie Winston',
  'Courage My Love',
  'Daft Punk',
  'Future of Forestry',
  'Gorillaz',
  'Kate Boy',
  'Lets Be Friends',
  'nanobii',
  'Pendulum',
  'Pharell Williams',
  'The Prodigy',
  'Rusko',
  'SOIL&"PIMP"SESSIONS',
  'This Town Needs Guns',
  'Bag Raiders',
  'Superfruit',
  'Grant',
  'MMG',
  'Mitch and Mike Gordon',
  'Mitch & Mike Gordon',
  'Oliver',
  'MisterWives',
  'Virtual Self',
  'Rikashay',
  'Big Wild',
  'Anomalie',
  'What So Not',
  'Opiuo',
  'Lorde',
  'Bo En',
  'San Holo',
  'Kasbo',
  'MOONZz',
  'Remo Drive',
  'Snarky Puppy',
  'Rivers Cuomo',
  'Jaden Smith',
  'Brohug',
  'Rob Araujo',
  'Deathpact',
  'bill wurtz',
  'KRANE',
  'k?d',
  'Mitski',
  'Run the Jewels',
  'Rezz',
  'Rilan and the Bombardiers',
  'SAINT PUNK',
  'LUCA LUSH',
  'Alexander Lewis',
  'billwurtz',
  'bill wurtz',
  'Too Many Zooz',
  'Lucy Daydream',
  'Jacob Collier',
  'Parcels',
  'Tritonal',
  'Flume',
  'Disclosure',
  'Bea Miller',
  'FRENSHIP',
  'Iris Temple',
  'Jaron',
  'Gold Complex',
  'Anna Lunoe',
  'FINNEAS',
  'Billie Eilish',
  'Rob Araujo',
  'Grynpyret',
  'Eliza Pope',
  'Lydia Persaud',
  'The Upper Tunist',
  'Ryn Weaver',
  'Virtual Self',
  'Vulfpeck',
  'The Fearless Flyers',
  'Anamanaguchi',
  'KNOWER',
  'Lawrence',
  'Franc Moody',
  'Galimatias',
  'Sure Sure',
  'Cory Wong',
  'Joey Dosik',
  'Theo Katzman',
  'Richard Garvey',
  'Tom Misch',
  'Magic City Hippies',
  'Louis Cole',
  'Parcels',
  'bbno$',
  'Howwler',
  'Sammy Rae',
  'Duskus',
  'TV Noise',
  'Don Diablo',
  'Brasstracks',
  'Alexander Lewis',
  'Bill Wurtz',
  'billwurtz',
  'Dua Lipa',
].freeze
