FILTER_ARTISTS_LIST = [
  "Maxo",
  "SWANES",
  "Lully",
  "Virtual Riot",
  "JOYRYDE",
  "Dillon Francis",
  "Ruby Empress",
  "WRLD",
  "Traxwell",
  "Rationale",
  "courtship",
  "Mat Zo",
  "Knife Party",
  "KSHMR",
  "Zedd",
  "Botnek",
  "Flume",
  "Boombox Cartel",
  "Kero Kero Bonito",
  "RKCB",
  "Tennyson",
  "PREP",
  "sundial",
  "Galantis",
  "Porter Robinson",
  "Gavin Turek",
  "Chiara Hunter",
  "Skogsrå",
  "SOPHIE",
  "Curbi",
  "Skylar Spence",
  "AWE",
  "Wave Racer",
  "Diveo",
  "Tundran",
  "Gammer",
  "Caravan Palace",
  "aivi & surasshu",
  "Lenno",
  "Billboard",
  "Robotaki",
  "Fox Stevenson",
  "Jay Prince",
  "RL Grime",
  "Cosmo's Midnight",
  "Goodnight Cody",
  "OK Go",
  "Chloe Martini",
  "Noisia",
  "bo en",
  "Disclosure",
  "Mystery Skulls",
  "ANAMANAGUCHI",
  "Jakubi",
  "Chromeo",
  "TOKYO MACHINE",
  "slenderbodies",
  "Haywyre",
  "grey",
  "Magic Man",
  "Lido",
  "Urban Cone",
  "Madeon",
  "CHVRCHES",
  "KOAN Sound",
  "The Colourist",
  "Chad Valley",
  "Aero Chord",
  "Charlie Winston",
  "Courage My Love",
  "Daft Punk",
  "Future of Forestry",
  "Gorillaz",
  "Kate Boy",
  "Lets Be Friends",
  "nanobii",
  "Pendulum",
  "Pharell Williams",
  "The Prodigy",
  "Rusko",
  "SOIL&\"PIMP\"SESSIONS",
  "This Town Needs Guns",
  "Bag Raiders",
]
